export const FILE_MIME_LABELS: Record<string, string> = {
  "application/pdf": "PDF",
  "application/msword": "Word",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "Word",
  "application/vnd.ms-excel": "Excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "Excel",
  "application/vnd.ms-powerpoint": "PowerPoint",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation": "PowerPoint",
  "text/csv": "CSV",
  "text/plain": "TXT",
};

export const FILE_MIME_ICONS: Record<string, string> = {
  "application/pdf": "file-pdf-box",
  "application/msword": "file-word-box",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "file-word-box",
  "application/vnd.ms-excel": "file-excel-box",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "file-excel-box",
  "application/vnd.ms-powerpoint": "file-powerpoint-box",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation": "file-powerpoint-box",
  "text/csv": "file-delimited",
  "text/plain": "file-document-outline",
  "image": "file-image",
  "video": "file-video",
  "audio": "file-music",
  "application": "file-document",
  "text": "file-document",
  "default": "file",
};

export const ALLOWED_MIME_TYPES: string[] = [
  "application/pdf",
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.ms-excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/vnd.ms-powerpoint",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "text/csv",
  "text/plain",
  "image/jpeg",
  "image/png",
  "image/gif",
  "image/webp",
  "video/mp4",
  "video/quicktime",
  "audio/mpeg",
  "audio/mp3",
  "audio/wav",
];

export const ALLOWED_EXTENSIONS: string[] = [
  ".pdf",
  ".doc",
  ".docx",
  ".xls",
  ".xlsx",
  ".ppt",
  ".pptx",
  ".csv",
  ".txt",
  ".jpg",
  ".jpeg",
  ".png",
  ".gif",
  ".webp",
  ".mp4",
  ".mov",
  ".mp3",
  ".wav",
];