import { StyleSheet } from "react-native";

export const profileIdStyles = StyleSheet.create({
  scrollContainer: {
    paddingHorizontal: 20,
    alignItems: "center",
    backgroundColor: "white",
    flex: 1,
  },
  centeredContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f4f6f8",
  },
  header: {
    alignItems: "center",
    marginVertical: 20,
  },
  avatar: {
    marginBottom: 12,
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 3,
    borderColor: "#ccc",
    backgroundColor: "#e0e0e0",
  },
  userName: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#333",
  },
  fullName: {
    fontSize: 20,
    fontWeight: "600",
    color: "#555",
    marginTop: 4,
  },
  inputCard: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 6,
    marginBottom: 15,
    paddingHorizontal: 15,
    paddingVertical: 10,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  label: {
    fontSize: 14,
    color: "#555",
    marginBottom: 6,
    fontWeight: "500",
  },
  readOnlyText: {
    textAlign: "justify",
    fontSize: 16,
    color: "#333",
  },
  email: {
    fontSize: 14,
    color: "#888",
    backgroundColor: "#fff",
    padding: 12,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 2,
  },
  loadingText: {
    fontSize: 18,
    color: "#333",
    marginTop: 10,
  },
  errorText: {
    fontSize: 18,
    color: "red",
    textAlign: "center",
    paddingHorizontal: 30,
  },
  joinDate: {
    fontSize: 14,
    color: "#888",
    marginTop: 6,
    fontStyle: "italic",
  },
});
